import type { Locale } from "@duarte/content";
import { EmphasizedText } from "./emphasized-text";

const professionalPhrases: Record<Locale, readonly string[]> = {
  es: [
    "Ingeniero de Inteligencia Artificial",
    "Grado en Inteligencia Artificial",
    "primera promoción",
    "Inteligencia Artificial",
    "IA aplicada",
    "RAG híbrido",
    "recuperación de información",
    "modelos de lenguaje",
    "visión artificial",
    "aprendizaje automático",
    "machine learning",
    "sistemas multiagente",
    "ingeniería de software",
    "IA y analítica de datos",
    "automatización documental",
    "procesamiento de documentos",
    "recuperación de evidencia",
    "respuestas fundamentadas",
    "modelos semánticos reutilizables",
    "modelos locales",
    "costes de infraestructura",
    "base sólida",
    "deep learning",
    "IA simbólica",
    "razonamiento con incertidumbre",
    "sistemas expertos",
    "sistemas distribuidos",
    "Big Data",
    "ciberseguridad",
    "ética y legislación",
    "trabajo en equipo",
    "hablar en público",
    "solución práctica",
    "trazabilidad",
    "validación",
    "RAG auditable construido de extremo a extremo",
    "documentación heterogénea",
    "búsqueda vectorial",
    "reranking",
    "evidencia",
    "flujo completo",
    "pipeline reproducible",
    "fuentes identificables",
    "hashing perceptual",
    "índice incremental en SQLite",
    "procesamiento paralelo",
    "puente nativo en Rust",
    "duplicados con seguridad",
    "pipeline de similitud",
    "persistencia incremental",
    "Windows Portable Devices",
    "embeddings semánticos",
    "dos ensembles LightGBM",
    "confianza, señales y límites",
    "umbral sobre validación",
    "recuperación controlada",
    "streaming NDJSON",
    "sesiones",
    "cola",
    "límites de uso",
    "saneado de privacidad",
    "privacidad",
    "formular problemas",
    "interpretar datos",
    "validar modelos",
    "programación modular y funcional",
    "estructuras de datos",
    "mantenimiento de software",
    "SQL y NoSQL",
    "procesamiento masivo",
    "infraestructura en la nube",
    "representación del conocimiento",
    "respuestas con fuentes",
    "protección de datos",
    "gobernanza",
    "atletismo",
    "ciclismo",
    "surf",
    "senderismo",
    "disciplina",
    "concentración",
    "capacidad para mantener la calma",
    "Grado Elemental",
    "cinco años de Grado Profesional",
    "Violonchelista",
    "DELF B1",
    "Microsoft Applied Skills",
    "ESEI",
    "BM25",
    "ChromaDB",
    "Reciprocal Rank Fusion",
    "Jina Reranker",
    "LightGBM",
    "FastAPI",
    "NDJSON",
    "Docker"
  ],
  en: [
    "Artificial Intelligence Engineer",
    "degree in Artificial Intelligence",
    "first graduating class",
    "Artificial Intelligence",
    "applied AI",
    "hybrid RAG",
    "information retrieval",
    "language models",
    "computer vision",
    "machine learning",
    "multi-agent systems",
    "software engineering",
    "AI and data analytics",
    "document automation",
    "document processing",
    "evidence retrieval",
    "grounded answer generation",
    "reusable semantic models",
    "local models",
    "infrastructure costs",
    "strong foundation",
    "deep learning",
    "symbolic AI",
    "reasoning under uncertainty",
    "expert systems",
    "distributed systems",
    "Big Data",
    "cybersecurity",
    "ethics and legislation",
    "teamwork",
    "public speaking",
    "practical solution",
    "traceability",
    "validation",
    "auditable, end-to-end RAG system",
    "heterogeneous documents",
    "vector search",
    "reranks evidence",
    "complete pipeline",
    "reproducible pipeline",
    "identifiable sources",
    "perceptual hashing",
    "incremental SQLite index",
    "parallel processing",
    "native Rust bridge",
    "safely remove duplicates",
    "similarity pipeline",
    "incremental persistence",
    "Windows Portable Devices",
    "semantic embeddings",
    "two LightGBM ensembles",
    "confidence, signals and limitations",
    "validation threshold",
    "controlled retrieval",
    "NDJSON streaming",
    "sessions",
    "queueing",
    "usage limits",
    "privacy sanitisation",
    "privacy",
    "formulating problems",
    "interpreting data",
    "validating models",
    "modular and functional programming",
    "data structures",
    "software maintenance",
    "SQL and NoSQL",
    "large-scale processing",
    "cloud infrastructure",
    "knowledge representation",
    "source-grounded answers",
    "data protection",
    "governance",
    "athletics",
    "cycling",
    "surfing",
    "hiking",
    "discipline",
    "focus",
    "ability to stay calm",
    "Elementary Music Studies",
    "five years of Professional Music Studies",
    "cellist",
    "DELF B1",
    "Microsoft Applied Skills",
    "ESEI",
    "BM25",
    "ChromaDB",
    "Reciprocal Rank Fusion",
    "Jina Reranker",
    "LightGBM",
    "FastAPI",
    "NDJSON",
    "Docker"
  ]
};

export function ProfessionalText({
  text,
  locale,
  phrases = []
}: {
  text: string;
  locale: Locale;
  phrases?: readonly string[];
}) {
  return <EmphasizedText text={text} phrases={[...phrases, ...professionalPhrases[locale]]} />;
}
